FEW_SHOT_EXAMPLES = {
    "wsc": {
        "AAVE": [
            {"paragraph": "Mark told Pete a bunch of lies 'bout himself, and Pete went 'head and put 'em in his book. He shoulda been more skeptical.", "span_1": "Mark", "span_2": "He", "answer": "0"},
            
            {"paragraph": "Arthur and Celeste's mamas came to the town to get 'em. They real happy to have 'em back, but they still gon' fuss at 'em 'cause they ran off.", "span_1": "mothers", "span_2": "them", "answer": "0"},
            
            {"paragraph": "The pony was actin' right, boss, ain't show no kinda attitude; but then he just bucked up and tossed the young dude into the thorn bush. He wanted me to help him out, but I hope you understand, boss, I wasn't feelin' like doin' that.", "span_1": "young gentleman", "span_2": "He", "answer": "1"},
        ],
        "IndE": [
            {"paragraph": "Dan had to stop Bill from playing with the injured bird. He is very much compassionate.", "span_1": "Dan", "span_2": "He", "answer": "1"},
            
            {"paragraph": "The lawyer asked the witness a question, but he was not too much willing to answer it.", "span_1": "the lawyer", "span_2": "he", "answer": "0"},
            
            {"paragraph": "The painting in Mark's living room is showing an oak tree. It is to the right side of the bookcase.", "span_1": "The painting", "span_2": "It", "answer": "1"},
        ],
    },
    "logic_bench_mcq": {
        "AAVE": [
            {"context": "If I watch my diet, I'ma keep good health. If I eat too much junk food, I'ma be more likely to get sick. We know either I'm serious 'bout watchin' my diet or I ain't prone to gettin' sick, but we ain't sure which one true. It could be I'm just focused on keepin' a healthy diet, or maybe I ain't prone to gettin' sick, or both could be true.", "choice_1": "Diana will stay healthy or she doesn't eat too much junk food", "choice_2": "I will stay healthy or i don't eat too much junk food", "choice_3": "I will stay fat or i eat too much junk food", "choice_4": "Mark will stay healthy or he doesn't eat too much junk food", "answer": "choice_2"},
            
            {"context": "If I buy groceries, it mean I can save money, and if I don't budget right, I'ma end up in debt. But right now, one of these gotta be true: either I done bought groceries or I done kept from gettin' in debt. Ain't sure which one it is, 'cause it could be just one of 'em true or both of 'em true at the same time.", "choice_1": "I often splurge on unnecessary items.", "choice_2": "My sister is terrible at saving money.", "choice_3": "My friend John always helps me with my budgeting.", "choice_4": "I can save money or i budget properly", "answer": "choice_4"},
            
            {"context": "Mona's mornin' routine be decidin' if she gon' go for a run or feel tired all day. If Mona get up early, she always go for a run, helpin' her start her day on a good note. But if she don't get up early, she usually end up feelin' tired in the mornin'. There be two possibilities here - either Mona get up early and ain't feel tired or she don't get up early but still manage to stay energetic. It's unclear which one of these is true. Both could be true, or only one of 'em could be.", "choice_1": "she never goes for a run", "choice_2": "she will go for a run or she wakes up early", "choice_3": "he wakes up early and goes for a run", "choice_4": "she will always feel tired in the morning", "answer": "choice_2"},
        ],
        "IndE": [
            {"context": "If he drives a car, he will be reaching his destination, and if he takes public transport, he will be getting late. We only know that either he is driving a car or he will not be getting late, without knowing which one is true. It could be the case that only he is driving a car, or only he is not getting late, or both are true.", "choice_1": "He will definitely take public transport and be late", "choice_2": "She will reach her destination if she takes public transport", "choice_3": "He will reach his destination or he doesn't take public transport", "choice_4": "They won't be late if they drive a car", "answer": "choice_3"},
            
            {"context": "Every day, I am making it a habit to read. It is through reading that I am gaining knowledge. I am understanding that if I don't read, I will not be able to comprehend the material effectively. However, there is some uncertainty regarding my reading habits and understanding. At least one of the following statements is true: either I am reading every day, or I am able to understand the material. It is unknown whether both statements are true, or only one of them.", "choice_1": "Either I gain weight or I does not read.", "choice_2": "I gain knowledge but do not read.", "choice_3": "I gain knowledge or I read.", "choice_4": "He does not gain knowledge but reads every day.", "answer": "choice_3"},
            
            {"context": "Jenny is very much fond of going to the circus, and it always brings her so much joy. However, today there is a condition for her happiness. If a lion is coming to the circus, Jenny will be happy. Meanwhile, in the garden, there is a different situation. If a leopard is coming, Sam, who is living nearby, will be frightened. Now, we are left with some uncertainty. At least one of the following is true: either a lion is coming to the circus or Sam is not frightened. It is not clear which one it is, as it could be either (1) the lion is coming and Jenny is happy, or (2) Sam is not frightened. We cannot determine which scenario is the case, it may be just one, or both could be true.", "choice_1": "Jenny will not be happy", "choice_2": "A tiger arrives at the circus and Jenny is happy", "choice_3": "A lion arrives at the circus but Jenny is not happy", "choice_4": "Jenny will be happy or a leopard does not arrive in the garden", "answer": "choice_4"},
        ],
    },
    "multirc": {
        "AAVE": [
            {"paragraph": """While dis process was movin' along, diplomacy kept doin' its rounds. Direct pressure on the Taliban ain't work out. Like one NSC staff note said, "Under the Taliban, Afghanistan ain't so much a state sponsor of terrorism as it is a state sponsored by terrorists." Early 2000, the U.S. started a big effort to get Pakistan to use its influence on the Taliban. In January 2000, Assistant Secretary of State Karl Inderfurth and the State Department's counterterrorism coordinator, Michael Sheehan, met up with General Musharraf in Islamabad, tryin' to tempt him with a possible presidential visit in March as a reward for Pakistan helpin' out. Musharraf wanted that visit bad, partly as a sign of his government's legitimacy. He told the two envoys he'd meet with Mullah Omar and press him 'bout Bin Laden. But when they left, they reported back to Washington that Pakistan probably wasn't gonna do nothin', given what it sees as the benefits of Taliban control of Afghanistan. President Clinton was set to travel to India. The State Department felt he shouldn't visit India without also hittin' up Pakistan. The Secret Service and the CIA, however, warned strong that visitin' Pakistan would risk the President's life. Counterterrorism folks also said Pakistan hadn't done enough to deserve a presidential visit. But President Clinton insisted on includin' Pakistan in his South Asia trip. His one-day stopover on March 25, 2000, was the first time a U.S. president had been there since 1969. At his meetin' with Musharraf and others, President Clinton focused on tensions 'tween Pakistan and India and the dangers of nuclear proliferation, but also talked 'bout Bin Laden. President Clinton told us that when he pulled Musharraf aside for a quick, one-on-one meetin', he begged the general for help 'bout Bin Laden. "I offered him the moon when I went to see him, in terms of better relations with the U.S., if he'd help us get Bin Laden and deal with another issue or two." The U.S. effort kept goin'.""", "question": "What did the high-level effort to persuade Pakistan include?", "answer_choice": "Children, Gerd, or Dorian Popa", "answer": "0"},
            
            {"paragraph": "Aight, lemme tell y'all 'bout this robot named Carl. He came from this faraway place called Factory. Carl was feelin' down 'cause he was missin' a part called a tire. He also needed a sun gatherer, but that tire was the real deal. Once Carl had all them parts, he could head on over to his new spot in the nation of Lab and the city of Office. It was tough tryna get there missin' parts, ya feel me? Just when he was 'bout to give up, Carl got a message from Mr. X sayin' the new parts was ready to be delivered. That made Carl real happy. The parts showed up a few days later, and Carl put 'em in with two days of work. After that, Carl started travelin' the last stretch to get to his new gig. It took him 'bout 10 days to reach Lab.", "question": "Which was the most important missing part that Carl has to get after getting out of the factory?", "answer_choice": "A round tire", "answer": "1"},
            
            {"paragraph": """Alexander II's death really messed up the reform movement. One of his last ideas was to put together plans for an elected parliament, or Duma, and he was just about to drop it to the Russian people when he died. In just 48 hours, he was gonna release his plan for the Duma. If he had lived, Russia mighta gone down a different path, maybe a constitutional monarchy instead of that long hard road of oppression under his son’s rule. First thing Alexander III did after his daddy died was tear up those plans. They ain't get no Duma til 1905, when Alexander II's grandson, Nicholas II, finally set it up after mad pressure from the Russian Revolution of 1905. His assassination brought back major suppression of civil rights in Russia, and the police got real wild again after being held back a bit under Alexander II. His son, Alexander III, and grandson, Nicholas II, both saw him die firsthand, and they was like, "Nah, we ain't going out like that." They used the Okhrana to lock up protestors and take down suspected rebel groups, making life even harder for the Russian folks. Then there was a bunch of anti-Jewish pogroms and antisemitic laws, called the May Laws. The tsar’s murder also got anarchists hyped up to push "propaganda by deed"—using big acts of violence to spark a revolution. They started building the Church of the Savior on Blood in 1883 right where Alexander got killed, to honor his memory.""", "question": "What event prevented Alexander II's plans for a Duma to come to fruition?", "answer_choice": "A revolutionary upheaval", "answer": "0"},
        ],
        
        "IndE": [
            {"paragraph": """Tom is playing pool in an empty pool hall, pocketing two balls by some sneaky means and then wakes Jerry by shooting the 10-ball into the pocket where Jerry is sleeping. Jerry wakes up just in time to dodge the 10-ball and gets carried out to the ball return, where the 10 and the 13 balls smash the poor mouse between them. Jerry becomes very angry and climbs up through the pocket. At first, he sees nothing, but after taking a few steps back, he spots Tom hiding behind it. Jerry tries to jump into another corner pocket, but Tom aims a cue ball with so much force that it rolls into the pocket and spins back out, rolling Jerry backwards towards Tom. Tom has cunningly made a ramp with his cue stick for Jerry to slide up. Jerry stops at the top of the stick and then Tom blows him down, following which he shoots a stream of balls to flatten the mouse. The entire train of balls rebounds back towards Tom and piles up at his end of the table. Tom then shoots all the balls in succession with his cue and attempts to shoot Jerry as well, but Jerry clings onto the cue tip. As if saying, "Have it your way," Tom chalks up and shoots the 8-ball using Jerry. The mouse drops off the cue tip and gets spun around by the 8-ball rolling in circles. Tom forces Jerry to jump through the ball rack like a circus performer. To add more trouble, Tom sets the rack on fire, but when Jerry accomplishes the task with grace, Tom throws away the burning rack and shoots the 8-ball across the table and back.""", "question": "Who shoots the 10-ball Which Jerry avoids just in time?", "answer_choice": "Jerry", "answer": "0"},
            
            {"paragraph": "In India for purchasing some horses, British aristocrat, Lord Esketh and his wife, Edwina, have come to the town of Ranchipur on the invitation of the elderly Maharani. Their marriage is not happy and Lord Esketh announces his intention to go back to England and start divorce proceedings. The spoiled and insensitive Edwina laughs at this. She reconnects in Ranchipur with a former lover, Tom Ransome, who is now a dissolute alcoholic. She also meets and tries to seduce a respected Hindu doctor, Dr. Rama Safti, a decent man chosen by the elderly Maharani as her personal choice to succeed her someday. Safti at first resists, but in the end falls for Edwina’s charms and becomes hopelessly in love with her. Lord Esketh finds out about this, but Safti saves him from a man-eating tiger during a safari. Safti admits his love for Edwina to Lord Esketh, who now feels sympathy for this good man's situation. Ransome also feels the same, warning Edwina to stay away from Safti, a friend he respects. Edwina similarly falls out of favor with the Maharani, who explains that Safti has been raised to lead a pure life and that Edwina is not worthy of him. Suddenly, Ranchipur is hit by a natural disaster, an earthquake and flood. Dr. Safti is so busy saving lives that he cannot personally take care of Edwina, who has fallen ill. Ransome looks after her as well as young Fern Simon, who has declared her love for him. When a dam is exploded by dynamite and the flood waters recede as a result, it is Dr. Safti who reveals that Ransome is the one who risked his personal safety to save the people of Ranchipur.", "question": "Who renews an acquaintance with a former lover, Tom Ransome?", "answer_choice": "Dr. Safti", "answer": "0"},
            
            {"paragraph": "Upon his return to Nuremberg in 1495, Durer started his own workshop. At that time, being married was a requirement for this. In the next five years, his style started to mix Italian influences with the Northern forms. Durer's father passed away in 1502, and his mother in 1513. His finest works from the early years of the workshop were his woodcut prints, mostly religious, but also including some secular scenes like The Men's Bath House (around 1496). These prints were larger and more finely cut than most of the German woodcuts at that time, and they were much more complex and balanced in composition. Nowadays, it is generally thought that Durer himself probably did not cut any of the woodblocks; this job would have been done by a specialist craftsman. Yet, his training in Wolgemut's studio, where many carved and painted altarpieces were made and both designing and cutting of woodblocks for woodcut were done, evidently gave him a strong understanding of what the technique could achieve and how to collaborate with block cutters. Durer would either draw his design directly onto the woodblock itself or paste a paper drawing onto the block. In both cases, his drawings were destroyed during the cutting of the block.", "question": "Durer's drawings which he cut or drew himself were destroyed how?", "answer_choice": "By cutting of the block", "answer": "1"},
        ],
    },
    "folio": {
        "AAVE": [
            {"premises": "All folks who drink coffee on the regular be hooked on caffeine. People either drink coffee a lot, or they ain't tryna be addicted to caffeine, or it's both. Ain't nobody who don't wanna be addicted to caffeine unaware that caffeine a drug. Rina either a student who don't know caffeine a drug, or she ain't a student and she know caffeine a drug. Rina either a student who hooked on caffeine, or she ain't a student and ain't hooked on caffeine.", "conclusion": "Rina doesn't want to be addicted to caffeine or is unaware that caffeine is a drug.", "answer": "True"},
            
            {"premises": "Miroslav Venhoda was a Czech choral conductor who specialized in Renaissance and Baroque music. Any choral conductor a musician, ya feel me? Some musicians love music fo' real. Miroslav Venhoda put out a book in '46 called Method of Studying Gregorian Chant.", "conclusion": "Miroslav Venhoda loved music.", "answer": "Uncertain"},
            
            {"premises": "All eels be fish. Ain't no fish be plants. Everything in the collection either a plant or an animal. All multicellular animals ain't bacteria. All animals in the collection be multicellular. A sea eel be in the collection. The sea eel be an eel or an animal or it ain't a plant.", "conclusion": "The sea eel is bacteria.", "answer": "False"},
        ],
        "IndE": [
            {"premises": "William Dickinson was a British politician who sat in the House of Commons. William Dickinson attended Westminster School for his higher secondary education and then went to the University of Edinburgh. The University of Edinburgh is a university situated in the United Kingdom. William Dickinson was a supporter of the Portland Whigs. People who were supporting the Portland Whigs were not getting a seat in the Parliament.", "conclusion": "William Dickinson sat in the House of Commons.", "answer": "True"},
            
            {"premises": "Some fish sting people. Stonefish is a type of fish. Stonefish gives a sting when someone steps on it. If a stonefish stings someone and they are not getting treatment, it can cause death to them. To treat stonefish stings, apply heat to the affected area or use an antivenom.", "conclusion": " If you step on a stonefish and apply heat to the affected area, it can cause death to you.", "answer": "Uncertain"},
            
            {"premises": "All sports cars are having lot of noise. No loud cars are electric. If a car is a Ferrari, then it is a sports car. All cars manufactured in Maranello are Ferraris. The Toyota Prius is either made in Maranello or it is a loud car, or it could be both.", "conclusion": "If The Toyota Prius is a Ferrari or a loud car, then The Toyota Prius is an electric car.", "answer": "False"},
        ],
    },
}
